config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'password'
    end
  end

  resources :projects do
  end

  resources :projects, only: [:show,] do
    resources :courses, only: [:show] do
      resources :supporters, only: [:new, :create] do
        collection do
          post 'confirm'
        end
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :supporters
  has_many :users, through: :supporters

  belongs_to :project, optional: true

  validates :name,        presence: true,      length: { maximum: 40 }
  validates :body,        presence: true,      length: { maximum: 200 }
  validates :price,       presence: true
  validates :image,       presence: true
  validates :stock,       presence: true
  validates :delivery,    presence: true

end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :user
  has_many :courses
  accepts_nested_attributes_for :courses

  validates :title,       presence: true,      length: { maximum: 20 }
  validates :target_fig,  presence: true,      length: { maximum: 7 }
  validates :end_time,    presence: true
  validates :image,       presence: true
  validates :body,        presence: true

  def clear_rate
    self.courses.map{|course|(course.supporters.count)*(course.price)}.sum/(self.target_fig.to_i).to_f*100
  end

  def sum_price
    self.courses.map{|course|(course.supporters.count)*course.price}.sum
  end


end

app/models/supporter.rb
class Supporter < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :gender, presence: true
  validates :birthday, presence: true ,        length: { maximum: 10 }
  validates :mobile, presence: true,          length: { maximum: 11 }
  validates :postal_code, presence: true,    length: { maximum: 7}
  validates :region, presence: true
  validates :city, presence: true
  validates :block, presence: true
  validates :building, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader

  has_many :projects
  has_many :supporters
  has_many :courses, through: :supporters

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @projects = Project.order(created_at: :DESC).limit(9)
    @new_projects = Project.order(created_at: :DESC).limit(8)
  end

  def show
    @project = Project.includes(:courses).find(params[:id])
  end



  def new
    @project = Project.new
    @project.courses.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path, notice: "企画が投稿されました。"
    else
      flash.now[:alert] = "未入力項目があります。"
      # redirect_to new_project_path, alert: "未入力項目があります。"
      render :new
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :target_fig, :end_time, :image, :body, courses_attributes: [:name, :body, :price, :image, :stock, :delivery]).merge(planner_id: current_user.id)
  end

end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  before_action :set_course, only: [:new, :create, :confirm]

  def new
    @supporter = @course.supporters.new
  end

  def create
    @supporter  = current_user.supporters.new(supporter_params)
    if params[:back]
      render :new
    elsif @supporter.save
      redirect_to root_path , notice: "ご支援ありがとうございました。"
    else
      flash.now[:alert] = "支援できませんでした。"
      render :new
    end
  end

  def confirm
    @supporter  = current_user.supporters.new(supporter_params)
    if @supporter.invalid?
      flash.now[:alert] = "未入力項目があります。"
      render :new
    end
  end

  private
  def supporter_params
    params.require(:supporter).permit(:name, :gender, :birthday, :mobile, :postal_code, :region, :city, :block, :building).merge(course_id: params[:course_id])
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :edit, :password]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      redirect_to root_path, notice:"プロフィール情報が編集されました。"
    else
      flash.now[:alert] = "プロフィール編集が失敗しました。"
      render :edit
    end
  end

  def password
  end

  private
  def user_params
    params.require(:user).permit(:name, :image, :email, :location, :birthday, :gender, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
    @hold_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/supporter_helper.rb
module SupporterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/show.html.haml
.header
  .inbox
    = link_to "/" do
      = image_tag("makuake-logo.png", class: "inbox__logo")
.main
  .main__course
    %ul.course__header
      %li.course__header-list.list-select  1.支払方法の選択
      %li.course__header-list 2.お届け先の入力
      %li.course__header-list 3.申込み内容の確認
      %li.course__header-list.list-last 4.完了
    .course__menu
      %h2.course__menu__title 選択中のコース
      = link_to "変更する", project_path(@course.project), class: "course__menu-link"
    .course__detail
      = image_tag("#{@course.image}", class: "course__detail-image")
      .course__detail__main
        .course__detail__main-price #{@course.price.to_s(:delimited)}円コース(税込)
        .course__detail__main-title #{@course.name}
        .course__detail__main-body #{simple_format(@course.body)}
    .course__menu
      %h2.course__menu__title 支払い方法を選択する
      .course__menu__text
        合計金額が1,000円(税込)以上の場合、クレジットカード以外の決済手段もご利用可能です。支払い方法の詳細については
        = link_to "ヘルプ", "", class: "course__menu__text-link"
        をご覧ください。
    .course__detail
      .course__detail__pay
        %ul.pay__select
          %li.pay__select-list クレジットカード
          %li.pay__select-list コンビニ支払い
          %li.pay__select-list 銀行振込
          %li.pay__select-list.list-last ネットバンク振込
        = image_tag("convenience.gif", class: "pay__image-convenience")
    .btn__field
      = link_to "次へ", new_project_course_supporter_path(@course.project_id, @course.id), class: "next__btn"
  .caution__box
    %p ご確認お願いします
    %p このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。※Makuakeは、プロジェクトオーナーのプロジェクトが必ず成功することや、プロジェクトの品質、リターン内容を保証するものではありません。従って、プロジェクト進行中に関するトラブル、返金要求、リターン返品要求はプロジェクトオーナーの責任のもと行われます。
    %p セキュリティについて
    .caution__inbox
      = image_tag("siteSealImage.gif", class: "caution__inbox-image")
      %p.caution__inbox-text サイトはSSL暗号化通信に対応しておりますので、入力した情報は安全に送信されます。

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/projects/_header.html.haml
.header
  = link_to root_path do
    = image_tag("makuake-logo.png", class: "header__logo")

  .search__form
    = form_tag(root_path, method: :get) do
      %input.search__form__box{name: "title"}
      %label
        %input.search__form__btn{type: "submit", value: "探す"}
        %i.search__form__btn__image{class: "fa fa-search faa-ring animated"}

  - if user_signed_in?
    .navbar__signed
      %ul.navbar__signed__box
        %li
          = link_to  "プロジェクトを掲載する", new_project_path, class: "navbar__signed__box__link__apply"
        %li
          .navbar__signed__box__fav
            = link_to root_path do
              %i.navbar__signed__box__fav__icon{class: "fa fa-heart-o faa-pulse animated"}
        %li
          .navbar__signed__box__mail
            = link_to root_path do
              %i.navbar__signed__box__mail__icon{class: "fa fa-envelope-o"}
        %li
          .navbar__signed__box__bell
            = link_to root_path do
              %i.navbar__signed__box__bell__icon{class: "fa fa-bell-o"}
        %li
          .navbar__signed__box__user
            = link_to user_path(current_user) do
              = image_tag("icon_red.png", size: "26x26", class: "navbar__signed__box__user__icon")
        %li
          .navbar__signed__box__sign-out
            = link_to destroy_user_session_path do
              %i.navbar__signed__box__sign-out__icon{class: "fa fa-sign-out"}

  - else
    .navbar
      %ul.navbar__box
        %li
          = link_to "プロジェクトを掲載する", new_project_path, class: "navbar__box__link__apply"
        %li
          .navbar__box__fav
            = link_to root_path do
              %i.navbar__box__fav__heart{class: "fa fa-heart-o faa-pulse animated"} お気に入り
        %li
          .navbar__box__login
            = link_to "ログイン", new_user_session_path, class: "navbar__box__login__text"
        %li
          .navbar__box__signin
            = link_to "新規登録", new_user_registration_path, class: "navbar__box__signin__text"

app/views/projects/index.html.haml
= render partial: "header"
= render partial: "pickup"
= render partial: "content"
= render partial: "footer"

app/views/projects/new.html.haml
= render partial: "header"
.post__view
  .post
    %h1.post__title プロジェクト投稿
    %p.post__copy こんな感じの画面で投稿するのでしょうか。想像で作っています。
    / %p.post__copy{style: "color: red; font-size: 24px;"} データ登録機能は工事中です！
    / %p.post__copy{style: "color: red; font-size: 24px;"} 投稿するボタンを押しても動きません。
  .post__form
    = form_for (@project), url: projects_path do |f|
      .post__form__project
        .post__form__project-border
        %p.post__copy まず、下記に企画内容を入力しましょう。
        %p.post__copy 全項目入力必須です。魅力たっぷりのあなたの企画をアピールしましょう。
        .post__form__project-border
      .newproject__post__area
        .post__field
          .post__field__text 企画タイトル
          = f.text_field :title, class: 'post__field__box form-short', placeholder: '例）20文字以内', maxlength: "50"
        - if @project.errors.full_messages_for(:title).any?
          .post__error メインタイトルを入力してください。
        .post__field
          .post__field__text 目標金額
          = f.text_field :target_fig, class: 'post__field__box form-short', placeholder: '例）210000', maxlength: "7"
        - if @project.errors.full_messages_for(:target_fig).any?
          .post__error 目標金額を入力してください。
        .post__field
          .post__field__text 期日
          = f.text_field :end_time, class: 'post__field__box form-short', placeholder: '例）2017-03-22'
        - if @project.errors.full_messages_for(:end_time).any?
          .post__error 期日を入力してください。
        .post__field
          .post__field__text メインイメージ
          .input-file
            = f.file_field :image, class: "input-file" do
              %span 選択されていません
        - if @project.errors.full_messages_for(:image).any?
          .post__error__image メインイメージを選択してください。
        .post__field
          .post__field__text 企画詳細文
          = f.text_area :body, class: 'post__field__box form-long'
        - if @project.errors.full_messages_for(:body).any?
          .post__error 企画詳細文を入力してください。
      / .btn__area__newproject
      /   .title__btn__area
      /     %i.title__plus#title__plus{class: "fa fa-plus-square-o", style:"font-size:22px"}
      /       .title__plus-text タイトルを追加する
      /     %i.title__minus#title__minus{class: "fa fa-minus-square-o", style:"font-size:22px"}
      /       .title__minus-text タイトルを削除する
      /   .body__btn__area
      /     %i.body__plus#body__plus{class: "fa fa-file-text-o", style:"font-size:22px"}
      /       .body__plus-text テキストを追加する
      /     %i.body__minus#body__minus{class: "fa fa-file-text-o", style:"font-size:22px"}
      /       .body__minus-text テキストを削除する
      /   .image__btn__area
      /     %i.image__plus#image__plus{class: "fa fa-file-image-o", style:"font-size:22px"}
      /       .image__plus-text イメージを追加する
      /     %i.image__minus#image__minus{class: "fa fa-file-image-o", style:"font-size:22px"}
      /       .image__minus-text イメージを削除する
      / .post__form__project
      /   .post__form__project-border
      / .tag__form#tag__form
      /   .tag__input__area
      /     .tag__input__area-text タグ
      /     = text_field_tag 'project[genre_list][]', "", class: 'tag__input__area-box', placeholder: '例）お肉'
      /   .tag__btn__are
      /     %i.plus__btn{class: "fa fa-plus-square-o", id: "tag__plus"}
      /       .plus__text タグを追加する
      /     %i.minus__btn{class: "fa fa-minus-square-o", id: "tag__minus"}
      /       .minus__text タグを削除する
      .post__form__project
        .post__form__project-border
        %p.post__copy 次に支援者様へのリターンを入力しましょう。
        %p.post__copy こちらも全項目入力必須です。魅力的なリターンを用意しましょう。
        .post__form__project-border
      = f.fields_for :courses do |i|
        .form__box
          .post__field
            .post__field__text リターンタイトル
            = i.text_field :name, class: 'post__field__box form-short', placeholder: '例）40文字以内', maxlength: "40"
          - if @project.courses[i.index].errors.full_messages_for(:name).any?
            .post__error リターンタイトルを入力してください。
          .post__field
            .post__field__text リターン詳細文
            = i.text_area :body, class: 'post__field__box form-long'
          - if @project.courses[i.index].errors.full_messages_for(:body).any?
            .post__error 詳細文を入力してください。
          .post__field
            .post__field__text 金額
            = i.text_field :price, class: 'post__field__box form-short', placeholder: '例）10000', maxlength: "6"
          - if @project.courses[i.index].errors.full_messages_for(:price).any?
            .post__error 金額を入力してください。
          .post__field
            .post__field__text リターン用画像
            .input-file
              = i.file_field :image, class: "input-file" do
                %span 選択されていません
          - if @project.courses[i.index].errors.full_messages_for(:image).any?
            .post__error__image 画像を選択してください。
          .post__field
            .post__field__text 用意個数
            = i.text_field :stock, class: 'post__field__box form-short', placeholder: '例）20', maxlength: "3"
          - if @project.courses[i.index].errors.full_messages_for(:stock).any?
            .post__error 用意している個数を入力してください。
          .post__field
            .post__field__text 納品予定日
            = i.text_field :delivery, class: 'post__field__box form-short', placeholder: '例）2017-12-22', maxlength: "10"
          - if @project.courses[i.index].errors.full_messages_for(:delivery).any?
            .post__error 納品予定日を入力してください。
          / .post__form__project#border__under{data: {number: "#{i.index}"}}
          .post__form__project#border__under{data: {number: "#{i.index}"}}
            .post__form__project-border
      / %i.plus__btn{class: "fa fa-plus-square-o", id: "plus__btn"}
      /   .plus__text リターンを追加する
      / %i.minus__btn{class: "fa fa-minus-square-o", id: "minus__btn"}
      /   .minus__text リターンを削除する
      /
      / type: "button" の記述を除去すればデータ登録可能
      / = f.submit "投稿する", class: "post__btn", id: "project__submit__btn", type: "button"
      = f.submit "投稿する", class: "post__btn", id: "project__submit__btn"

= render partial: "footer"

app/views/projects/show.html.haml
= render partial: "header"
.project__main
  .project__header
    .project__header__box
      .project__header__link
        = link_to "TOP  >  ", "/", class: "project__header__link-text"
        = link_to "プロジェクト一覧", "/", class: "project__header__link-text"
        / .project__header__link-text #{@project.title}
      .project__menu
        = link_to "プロジェクト", "/", class: "nav-btn"
        = link_to "活動レポート", "/", class: "nav-btn"
        = link_to "応援コメント", "/", class: "nav-btn"
  .project
    = image_tag("#{@project.image}", class: "project__main__image")
    .project__main__detail
      %dl
        .st__money
          - if @project.clear_rate.round(0) >= 100
            = image_tag("success2.png", class: "st__money-success")
          %project__main__detail
            = image_tag("yen-white.png", class: "st__money-icon")
            .st__money-title 集まっている金額
          %dd.st__money-num #{@project.sum_price.to_s(:delimited)}円
          .st__money-goal 目標金額 #{(@project.target_fig.to_i).to_s(:delimited)}円
      .money__gage.st__money-gage
        - if @project.clear_rate.round(0) >= 100
          .money__gage__in{style: "width:270px" }
            .money__gage__in__percent #{@project.clear_rate.round(0)}%
        - else
          .money__gage__in{style: "width:#{270 * @project.clear_rate.round(0) / 100}px" }
            .money__gage__in__percent #{@project.clear_rate.round(0)}%
      %dl
        %dt
          = image_tag("people-white.png", class: "st__money__supporter-icon")
          .st__money__supporter-name サポーター
        %dd.st__money__supporter-count #{@project.courses.map{|course|(course.supporters.count)}.sum}人
      %dl
        %dt
          = image_tag("clock-white.png", class: "st__money__limit-icon")
          .st__money__limit-title 残り
        - if ((@project.end_time - Date.today).to_i) <= 0
          %dd.st__money__limit-days 期限切れ
        - else
          %dd.st__money__limit-days #{(@project.end_time - Date.today).to_i}日
      / .st__money-btn#st__money-btn 支援するコースを選択する
      = link_to "支援するコースを選択する", project_path(@project.id), class: "st__money-btn", type: "button"

    .project__main__name
      .project__main__name-text #{@project.title}
      / - @project.genre_list.each do |tag|
      /   .tag__btn
    .project__left
      .project__detail
        %p #{@project.body}
        / - if project.has_attribute?(:title)
        /   .project__detail__border
        /   .project__detail__block #{@project.title}
        /   .project__detail__border
        / - elsif project.has_attribute?(:body)
        /   .project__detail__body
        / - else
        /   = image_tag("#{@project.image}", class: "project__detail__image")
      .project__detail__bottom
        / .investments__btn#investments__btn 支援するコースを選択する
      / = image_tag("logo1.png", class: "project__detail__bottom-image")
      / .project__detail__logo-text “まだここにない”を手に入れよう
      / .project__detail__bottom-box
      /   = image_tag("main_project.jpg", class: "project__detail__bottom-box-image")
      /   .project__detail__bottom-box-fb-link
      /     %p.detail__fb-link-text
      /       このプロジェクトが気に入ったら
      /       %br
      /         %span.detail__fb-link-text-span いいね!
      /         をしよう
    .project__right
      .investments__bar#investments__bar
        .investments__bar__title 支援するコースを選択する
        .investments__bar__text このプロジェクトは目標金額の達成有無にかかわらず、サポーターがプロジェクトに支援を申し込んだ時点でプロジェクトの成立（売買契約の成立）となります。
        - @project.courses.each do |course|
          .investments__bar__menu
            .investments__bar__menu-money
              #{course.price.to_s(:delimited)}円コース
              %span.investments__bar__menu-tax (税込)
            .investments__bar__menu-qty 残り#{(course.stock.to_i)}個
          .investments__bar__detail
            .investments__bar__detail-title #{course.name}
            = image_tag("#{course.image}", class: "investments__bar__detail-image")
            .investments__bar__detail-body #{simple_format(course.body)}
            .investments__supporter-count
              = image_tag("black-people.png", class: "investments__supporter-count-image")
              .investments__supporter-count-text #{course.supporters.ids.count}人が支援しています。
            .investments__supporter-duedata
              = image_tag("bag.png", class: "investments__supporter-duedata-image")
              .investments__supporter-duedata-text #{course.delivery.strftime("%Y年%m月")}にお届け予定です。
          .investments__bar__link__box
            - if ((course.stock.to_i) ) == 0
              .stockout__btn 在庫切れ
            - else
              - if user_signed_in?
                = link_to "このコースに申し込む",project_course_path(@project, course), class: "order__btn"
              - else
                %a.order__btn{data: {toggle: "modal", target: "#my-modal-login-investments"}} このコースに申し込む
        .planner__inquiry
          .planner__inquiry-text 実行者へ問合せ
= render partial: "footer"

app/views/users/edit.html.haml
= render partial: "projects/header"
.mypage__edit
  .edit__left
    .mypage__left__box
      - if current_user.image.present?
        = image_tag("#{@user.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_red.png", class: "mypage__image", size: "175x175")
    .mypage__edit__name #{@hold_user.name}
    .mypage__main__left
      .mypage__border
      .mypage__menu__title
        %i.mypage__menu__title-image{class: "fa fa-group faa-pulse animated"}
        .mypage__menu__title-text サポーター
      .mypage__inbox
        .mypage__menu
          = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
      .mypage__inbox
        .mypage__menu
          = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メッセージ", "", class: "mypage__menu__body"
      .mypage__border
      .mypage__menu__title
        %i.mypage__menu__title-image{class: "fa fa-user faa-pulse animated"}
        .mypage__menu__title-text アカウント情報
      .mypage__inbox
        .mypage__menu
          = link_to "プロフィール編集", edit_user_path, class: "mypage__menu__body"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メール通知設定", "", class: "mypage__menu__body"
  .edit__right
    .mypage__main__right
      .right__title
        %h2 プロフィール編集
      = form_for (@user), url: user_path do |f|
        .profile__field
          .profile__field__text ユーザー名
          .profile__field__box
            = f.text_field :name, class: 'profile__field__box-form', placeholder: '例）hhiroki'
            - if @user.errors.full_messages_for(:name).any?
              .profile__error 名前を入力してください。
        .profile__field
          .profile__field__text プロフィール写真
          .profile__field__box
            = f.file_field :image, style: "margin-left:12px;"
        .profile__field
          .profile__field__text メールアドレス
          .profile__field__box
            = f.text_field :email, class: 'profile__field__box-form'
            - if @user.errors.full_messages_for(:email).any?
              .profile__error メールアドレスを入力してください。
        .profile__field
          .profile__field__text パスワード
          .profile__field__box
            = link_to "編集", password_user_path, class: "profile__pass__edit"
        .profile__field
          .profile__field__text 現在地
          .profile__field__box
            = f.text_field :location, class: 'profile__field__box-form'
        .profile__field
          .profile__field__text 誕生日
          .profile__field__box
            = f.text_field :birthday, class: 'profile__field__box-form'
        .profile__field
          .profile__field__text 性別
          .profile__field__box
            = f.text_field :gender, class: 'profile__field__box-form'
        .profile__submit
          = f.submit "変更する", class: "profile__submit__btn"
= render partial: "projects/footer"

app/views/users/password.html.haml
= render partial: "projects/header"
.mypage__edit
  .edit__left
    .mypage__left__box
      - if current_user.image.present?
        = image_tag("#{@user.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_red.png", class: "mypage__image", size: "175x175")
    .mypage__edit__name #{@hold_user.name}
    .mypage__main__left
      .mypage__border
      .mypage__menu__title
        %i.mypage__menu__title-image{class: "fa fa-group faa-pulse animated"}
        .mypage__menu__title-text サポーター
      .mypage__inbox
        .mypage__menu
          = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
      .mypage__inbox
        .mypage__menu
          = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メッセージ", "", class: "mypage__menu__body"
      .mypage__border
      .mypage__menu__title
        %i.mypage__menu__title-image{class: "fa fa-user faa-pulse animated"}
        .mypage__menu__title-text アカウント情報
      .mypage__inbox
        .mypage__menu
          = link_to "プロフィール編集", edit_user_path, class: "mypage__menu__body"
      .mypage__inbox.inbox__last
        .mypage__menu
          = link_to "メール通知設定", "", class: "mypage__menu__body"
  .edit__right
    .mypage__main__right
      .right__title
        %h2 パスワード変更
      = form_for (@user), url: user_path do |f|
        .profile__field
          = f.label :password, "新しいパスワード", class: 'profile__field__text'
          - if @minimum_password_length
            %em
              (#{@minimum_password_length} characters minimum)
            %br/
          .profile__field__box
            = f.password_field :password, class: 'profile__field__box-form'
        .profile__field
          = f.label :password_confirmation, "パスワード(確認)", class: 'profile__field__text'
          .profile__field__box
            = f.password_field :password_confirmation, class: 'profile__field__box-form'
        .profile__submit
          = f.submit "変更する", class: "profile__submit__btn"
= render partial: "projects/footer"

app/views/users/show.html.haml
= render partial: "projects/header"
.mypage__own
  .mypage__own__box
    .mypage__left__box
      - if current_user.image.present?
        = image_tag("#{current_user.image}", class: "mypage__image", size: "175x175")
      - else
        = image_tag("icon_red.png", class: "mypage__image", size: "175x175")
    .mypage__right__box
      .mypage__account-name #{current_user.name}
      .mypage__news
        .mypage__news__days 2017/10/02
        = link_to "【重要】 社名変更に伴う利用規約等変更のお知らせ", "", class: "mypage__news__body"
      .mypage__news
        .mypage__news__days 2017/07/05
        = link_to "【実行者様向け】7/11（火）システムメンテナンスのお知らせ", "", class: "mypage__news__body"
      .mypage__news
        .mypage__news__days 2017/06/13
        = link_to "【新機能】お気に入り＃タグ機能 の提供が開始されました！", "", class: "mypage__news__body"
      = link_to "お知らせ一覧を見る", "", class: "mypage__new__more"
.mypage__main
  .mypage__main__left
    .mypage__border
    .mypage__menu__title
      %i.mypage__menu__title-image{class: "fa fa-group faa-pulse animated"}
      .mypage__menu__title-text サポーター
    .mypage__inbox
      .mypage__menu
        = link_to "支援したプロジェクト", "", class: "mypage__menu__body"
    .mypage__inbox
      .mypage__menu
        = link_to "購入履歴(ストア)", "", class: "mypage__menu__body"
    .mypage__inbox.inbox__last
      .mypage__menu
        = link_to "メッセージ", "", class: "mypage__menu__body"
    .mypage__border
    .mypage__menu__title
      %i.mypage__menu__title-image{class: "fa fa-user faa-pulse animated"}
      .mypage__menu__title-text アカウント情報
    .mypage__inbox
      .mypage__menu
        = link_to "プロフィール編集", edit_user_path, class: "mypage__menu__body"
    .mypage__inbox.inbox__last
      .mypage__menu
        = link_to "メール通知設定", "", class: "mypage__menu__body"
  .mypage__main__right
    .right__title
      %h2 支援したプロジェクト
      = link_to "支援したプロジェクト一覧へ", "", class: "mypage__new__more"
    .right__body 支援しているプロジェクトはありません。
    .right__title
      %h2 購入履歴(ストア)
      = link_to "購入履歴(ストア)一覧へ", "", class: "mypage__new__more"
    .right__body 購入した商品はありません。
= render partial: "projects/footer"